# pr2:
  torso_lift_joint_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - torso_lift_joint
    gains:
      torso_lift_joint: {p: 100, i: 0.1, d: 1.0}
    constraints:
      goal_time: 10.0                  # Override default

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
