# pr2:
  r_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
    gains:
      r_shoulder_pan_joint: {p: 100, i: 0.01, d: 1}
      r_shoulder_lift_joint: {p: 100, i: 0.01, d: 1}
      r_upper_arm_roll_joint: {p: 100, i: 0.01, d: 1}
      r_elbow_flex_joint: {p: 100, i: 0.01, d: 1}
      r_forearm_roll_joint: {p: 100, i: 0.01, d: 1}
      r_wrist_flex_joint: {p: 100, i: 0.01, d: 1}
      r_wrist_roll_joint: {p: 100, i: 0.01, d: 1}

    constraints:
      goal_time: 10.0                  # Override default

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  l_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    gains:
      l_shoulder_pan_joint: {p: 100, i: 0.01, d: 1}
      l_shoulder_lift_joint: {p: 100, i: 0.01, d: 1}
      l_upper_arm_roll_joint: {p: 100, i: 0.01, d: 1}
      l_elbow_flex_joint: {p: 100, i: 0.01, d: 1}
      l_forearm_roll_joint: {p: 100, i: 0.01, d: 1}
      l_wrist_flex_joint: {p: 100, i: 0.01, d: 1}
      l_wrist_roll_joint: {p: 100, i: 0.01, d: 1}

    constraints:
      goal_time: 10.0                  # Override default

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
