# pr2:
  laser_tilt_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - laser_tilt_mount_joint
    gains:
      laser_tilt_mount_joint: {p: 8.0, i: 0.1, d: 0.2}
    constraints:
      goal_time: 10.0                  # Override default

    state_publish_rate:  50            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default